### PR TITLE
SOL-98655: Created sampler for JRTO Nack feature

### PR DESCRIPTION
**Pull request by aelsammak**
~~NOTE: Do not merge this PR until `jrto_nack` branch gets merged into trunk and the JRTO api dependency version is updated.~~

Change solclientJ to `10.5.0` when it becomes available in Maven repo

### CODE REVIEW

**Comment by aaron-613** [comment]
Hi @aelsammak .  Sorry for the delay on the review.  A couple things:
- there is no 10.4.1 version of `solclientj`.  (as referenced in the build file).  I believe the most recent version is 10.5.0 which should be going onto Maven shortly.  How did you get this to build?
- as there is no `main()` method, how did you test?  Or is it just intended as a snippet and not runnable?
    - if no test harness, should I code something up to test these methods work as expected?  Or can you provide something so I don't have to..?

Thanks!

**Comment by aelsammak** [comment]
> Hi @aelsammak . Sorry for the delay on the review. A couple things:
> 
> * there is no 10.4.1 version of `solclientj`.  (as referenced in the build file).  I believe the most recent version is 10.5.0 which should be going onto Maven shortly.  How did you get this to build?
> * as there is no `main()` method, how did you test?  Or is it just intended as a snippet and not runnable?
>   
>   * if no test harness, should I code something up to test these methods work as expected?  Or can you provide something so I don't have to..?
> 
> Thanks!

Hi @aaron-613, you are right, the solclientj version should be 10.5.0 which has the new settle functionality (10.4.1 was a typo, should have been 10.4.0 but it does not have the settle functionality). I can update it to the correct version when it becomes available in the Maven repo.

It is intended to just be a snippet and not runnable, hence there being no `main()` method. Ragnar mentioned that it is up to dev advocates to do something with the snippet, we just add the sample/snippet as not runnable code.

**Comment by aaron-613** [comment]
Hi @aelsammak , how are you?  I've finally got around to reviewing this PR after the holidays, now that the APIs have been released.  There was some issues with the code, some method signatures weren't correct.  It wouldn't build.  Was it building when you submitted it?  I don't believe the method signatures in `AbstractSample.MessageCallbackSample` had changed..?

Can you please review what I've done, and re-verify the snippets are coded correctly before I final review and merge this?

Thanks!

**Comment by aelsammak** [comment]
> Hi @aelsammak , how are you? I've finally got around to reviewing this PR after the holidays, now that the APIs have been released. There was some issues with the code, some method signatures weren't correct. It wouldn't build. Was it building when you submitted it? I don't believe the method signatures in `AbstractSample.MessageCallbackSample` had changed..?
> 
> Can you please review what I've done, and re-verify the snippets are coded correctly before I final review and merge this?
> 
> Thanks!

Hey @aaron-613, I am doing good! I was never actually able to build it since we were waiting for solclientj version 10.5.0 to be available on maven. However, I just checked out your changes and they LGTM! I was able to build it and the snippets look correct. 

Thank you 😄

**Comment by aaron-613** [comment]
I'm going to approve and merge.  Just one last (general) comment: I find it difficult when these examples/snippets use helper classes / methods in other files, in other packages... needing to jump around.  Other APIs do this too.  However I also understand the pain with code duplication, and easier to share common functions.  Just harder to read through.  Ah well, pros/cons either way.

Thanks!

**Pull request merged**
