### PR TITLE
SOL-61081: Created sampler for JRTO PQ feature.

### PR DESCRIPTION
**Pull request by TrentDaniel**

### CODE REVIEW

**Comment by Mrc0113** [comment]
@TrentDaniel should this still be a draft PR?

**Comment by TrentDaniel** [comment]
> @TrentDaniel should this still be a draft PR?

Probably not, I'll check that the feature has been released, then we can merge it

**Comment by aaron-613** [comment]
Hi @TrentDaniel .  Are you sure the code is ready to review?  Just loading the Java source code, my IDE is immediately complaining that there are 2 methods with duplicate signatures:
```
public void howToApplyQueuePartitionKey(MessageHandle messageHandle, String queuePartitionKey) throws SolclientException
```

It's also complaining about some `assertNull` statements... and there's no JUnit packages imported or anything.  Was this leftover test code?

Please reverify the code.  🙏🏼   Thanks!

**Comment by TrentDaniel** [comment]
@aaron-613 , fixed the typo, feel free to review the PR, not really sure who's in charge of that

**Comment by aaron-613** [comment]
Yup, fixes look good.

**Pull request merged**
